# -*- coding: utf-8 -*-
"""Tic Tac Toe.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RzjEYmGkojMYNc5ddABu0p3DhWx95QL2

#### Implementation of an Tic-Tac-Toe game using Python.
"""

import numpy as np

def create_board():
  board = np.array([['_','_','_'],
                    ['_','_','_'],
                    ['_','_','_']])

  return board

def place_mark(board, lst, player):
  r=lst[0]-1
  c=lst[1]-1
  if player == 1:
    board[r][c] = 'x'
  else:
    board[r][c] = 'o'
  return board

def check_win(board):
  if (any(all(board[i] == 'x')  for i in range(3))) | (any(all(board[:,i] == 'x')  for i in range(3))) | (all(board.diagonal() == 'x')) | (all(board[i][2-i] == 'x' for i in range(3))):
    print('Player 1 wins.')
    return 0
  elif (any(all(board[i] == 'o')  for i in range(3))) | (any(all(board[:,i] == 'o')  for i in range(3))) | (all(board.diagonal() == 'o')) | (all(board[i][2-i] == 'o' for i in range(3))):
    print('Player 2 wins.')
    return 0
  else:
    return 1

def print_board(board):
  for a in range(3):
   print(" | ".join( [str(b) for b in board[a]]))

def check_input(lst, inputs):
  if lst in inputs:
    print('Position already taken input other value')
    return 0
  else:
    return 1

print('Hello players. Enjoy The Tic Tac Toe Game !!')
print('')
board = create_board()
print_board(board)
print('')
game = 1
count = 9
inputs = []
while (count>0):
  if count%2 != 0:
    p=1
    v=0
    while v!=1:
      lst = list(map(int, input('Enter player 1: ').strip().split(',')))
      v=check_input(lst, inputs)
  else :
    p=2
    v=0
    while v!=1:
      lst = list(map(int, input('Enter player 2: ').strip().split(',')))
      v=check_input(lst, inputs)
  board = place_mark(board, lst, p)
  print('')
  print_board(board)
  print('')
  inputs.append(lst)
  game = check_win(board)
  if game:
    count -= 1
  else:
    print('Game Over')
    break
else:
  print('No one won')

